name: flutter_bloc_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0

  # Bloc
  bloc: ^8.1.4
  equatable: ^2.0.7
  flutter_bloc: ^8.1.6

  # Custom repo
  user_repository:
    path: packages/user_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
