name: post_repository
description: "Dart package which manages the posts."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7

  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0

  uuid: ^4.5.1

  user_repository:
    path: ../user_repository
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
